import os
import re
import requests
import anthropic
from datetime import datetime, timedelta, timezone
from pathlib import Path
from flask import Flask, jsonify, send_from_directory, request, session, redirect, url_for, render_template_string
from dotenv import load_dotenv
from functools import wraps
from google.oauth2 import id_token
from google.auth.transport import requests as google_requests

load_dotenv()

app = Flask(__name__, static_folder='static')
app.secret_key = os.environ.get('SECRET_KEY', 'crm-sales-training-2026')
app.config.update(SESSION_COOKIE_SAMESITE='Lax', SESSION_COOKIE_HTTPONLY=True,
                  SESSION_COOKIE_SECURE=os.environ.get('RAILWAY_ENVIRONMENT') is not None,
                  PERMANENT_SESSION_LIFETIME=timedelta(days=7))

# Google SSO — same OAuth client as the other CarCutter webapps (Pricing EU / AU-CA)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID',
                                  '77392442255-sn804nmg4rvr8d8psqpu3ku3kk50gv6t.apps.googleusercontent.com')
ALLOWED_DOMAIN = os.environ.get('ALLOWED_DOMAIN', 'carcutter.com')

TOKEN = os.environ.get('HUBSPOT_API_TOKEN', '')
BASE  = 'https://api.hubapi.com'
# Link to open a deal in HubSpot (EU data centre, portal 26533299)
HUBSPOT_DEAL_URL = os.environ.get('HUBSPOT_DEAL_URL', 'https://app-eu1.hubspot.com/contacts/26533299/record/0-3/{id}')

CLAUDE_MODEL = os.environ.get('CLAUDE_MODEL', 'claude-opus-5')

HOWTO_MD = (Path(__file__).parent / 'howto.md').read_text(encoding='utf-8')        # action-oriented cards
GUIDE_MD = (Path(__file__).parent / 'guidelines.md').read_text(encoding='utf-8')     # full reference

# The tool targets US Account Executives. "My deals" lists exactly these people
# (HubSpot owner IDs, emails or full names, comma-separated). Override with the SALES_REPS env var.
DEFAULT_SALES_REPS = ','.join([
    '35227458',  # Philip Tamez
    '31039261',  # Brian Paugh
    '30746930',  # Michael Lizza
    '76005619',  # Andrea Godin
    '29464368',  # Francisco Riba (active account)
    '30676601',  # Joshua Shanks
    '35550328',  # Jason Turner
    '29929356',  # James Norris
    '31130308',  # Zack (Zachary) Adamson
    '1711396065',  # Patrick Konczewski
])
SALES_REPS = {r.strip().lower() for r in os.environ.get('SALES_REPS', DEFAULT_SALES_REPS).split(',') if r.strip()}

# Fallback when SALES_REPS is empty: owners whose HubSpot team matches one of these words
SALES_TEAM_KEYWORDS = [k.strip().lower() for k in
                       os.environ.get('SALES_TEAM_KEYWORDS', 'sales,ae,bdr,smb').split(',') if k.strip()]

# Pipelines / stages (CarCutter)
NB_PIPELINE  = '56609227'    # CarCutter - New business
REN_PIPELINE = '228462803'   # CarCutter - Renewals & upsells

NB_WON   = {'141401056', '142518229', '142518230'}                # Closed won, Onboarding, Contract is live
NB_LOST  = {'141401057', '198382838'}                            # Closed lost, Rejected by AE
REN_WON  = {'390658251', '5600993472'}                            # Closed won, Contract is live
REN_LOST = {'390658252', '3504160964'}                           # Churned, Closed lost
REN_AUTO_STAGE = '390658246'                                     # Deal created (renewals generated by workflow)
EXPIRED_STAGES = {'5108653252', '5600993473'}                    # Contract has expired (NB, Renewals): not reviewed

# A renewal/upsell must be linked to the deal it replaces, labelled "Parent deal" on the old deal.
# Detected by the association label text (read from the new deal, the old one is its parent).
PARENT_LABEL_WORD = 'parent'

# Line items allowed on a "Set-up fees only" deal: showroom, integration, standing inventory processing
SETUP_ONLY_KEYWORDS = ('showroom', 'integration', 'intégration', 'inventory processing')
NB_CLOSED_WON, NB_ONBOARDING = '141401056', '142518229'

DEAL_PROPS = [
    'dealname', 'pipeline', 'dealstage', 'hubspot_owner_id', 'createdate', 'closedate', 'amount',
    'deal_currency_code', 'number_of_dealerships', 'number_of_locations_concerned_by_this_deal',
    'oem_brand', 'cars__product', 'company_legal_name', 'dms_ims_multiple_checkboxes',
    'renewal_type', 'num_associated_contacts', 'hs_num_of_associated_line_items',
    'contractdurationinmonths', 'setup_fees_only_no_recurring',
    'closed_lost_reason', 'closed_lost_reason___category',
]


# ── Auth ──────────────────────────────────────────────────────────────────────

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('user'):
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated


def api_login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('user'):
            return jsonify({'error': 'Unauthorized'}), 401
        return f(*args, **kwargs)
    return decorated


LOGIN_HTML = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>CRM Sales Training — Sign in</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://accounts.google.com/gsi/client" async defer></script>
</head>
<body class="bg-gray-50 min-h-screen flex items-center justify-center">
  <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-10 w-full max-w-sm text-center">
    <div class="w-10 h-10 rounded-xl bg-indigo-600 text-white font-bold flex items-center justify-center mx-auto mb-4">C</div>
    <h1 class="text-xl font-bold text-gray-800 mb-1">CRM Sales Training</h1>
    <p class="text-sm text-gray-400 mb-6">Sign in with your CarCutter account</p>
    <div id="g_id_onload"
      data-client_id="{{ client_id }}"
      data-callback="handleCredential"
      data-auto_select="{{ 'false' if signed_out else 'true' }}">
    </div>
    <div class="flex justify-center">
      <div class="g_id_signin" data-type="standard" data-theme="outline" data-size="large"
        data-text="signin_with" data-shape="rectangular" data-logo_alignment="left"></div>
    </div>
    <p id="auth-err" class="{% if not error %}hidden {% endif %}text-sm text-red-500 mt-4 bg-red-50 px-3 py-2 rounded-lg">{{ error or '' }}</p>
  </div>
  <script>
    async function handleCredential(r) {
      const err = document.getElementById('auth-err');
      const resp = await fetch('/auth/google', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ credential: r.credential }),
      });
      if (resp.ok) { location.href = '/'; return; }
      const data = await resp.json().catch(() => ({}));
      err.textContent = data.error || 'Sign-in failed';
      err.classList.remove('hidden');
      try { google.accounts.id.disableAutoSelect(); } catch (e) {}
    }
  </script>
</body>
</html>'''


@app.route('/login')
def login():
    if session.get('user'):
        return redirect(url_for('index'))
    return render_template_string(LOGIN_HTML, client_id=GOOGLE_CLIENT_ID, error=None,
                                  signed_out=request.args.get('signed_out') == '1')


@app.route('/auth/google', methods=['POST'])
def auth_google():
    """Verify the Google ID token server-side and open a session for @carcutter.com accounts only."""
    credential = (request.get_json(silent=True) or {}).get('credential', '')
    try:
        info = id_token.verify_oauth2_token(credential, google_requests.Request(), GOOGLE_CLIENT_ID)
    except ValueError:
        return jsonify({'error': 'Invalid Google sign-in, please try again.'}), 401

    email = (info.get('email') or '').lower()
    if not info.get('email_verified') or not email.endswith('@' + ALLOWED_DOMAIN):
        return jsonify({'error': f'Access restricted to CarCutter accounts (@{ALLOWED_DOMAIN}).'}), 403

    session.clear()
    session.permanent = True
    session['user'] = {'email': email, 'name': info.get('name') or email, 'picture': info.get('picture') or ''}
    return jsonify({'ok': True})


@app.route('/api/me')
@api_login_required
def me():
    return jsonify(session['user'])


@app.route('/logout')
def logout():
    session.clear()
    # signed_out=1 turns off Google auto-select so the user is not signed straight back in
    return redirect(url_for('login', signed_out=1))


@app.errorhandler(Exception)
def handle_any_error(e):
    import traceback
    traceback.print_exc()
    return jsonify({'error': f'{type(e).__name__}: {e}'}), 500


# ── HubSpot helpers ───────────────────────────────────────────────────────────

def make_session():
    s = requests.Session()
    s.headers.update({'Authorization': f'Bearer {TOKEN}'})
    return s


def slug(text):
    """Same slug as static/index.html so rules can link to a guide section."""
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


def get_stage_labels(s):
    resp = s.get(f'{BASE}/crm/v3/pipelines/deals', timeout=15)
    out = {}
    if resp.ok:
        for p in resp.json().get('results', []):
            for st in p.get('stages', []):
                out[st['id']] = st.get('label', st['id'])
    return out


def search_owner_deals(s, owner_id, since):
    """Deals of this owner in NB / Renewals created OR closed since `since`."""
    since_ms = str(int(since.timestamp() * 1000))
    base_filters = [
        {'propertyName': 'hubspot_owner_id', 'operator': 'EQ', 'value': str(owner_id)},
        {'propertyName': 'pipeline', 'operator': 'IN', 'values': [NB_PIPELINE, REN_PIPELINE]},
    ]
    body = {
        'filterGroups': [
            {'filters': base_filters + [{'propertyName': 'createdate', 'operator': 'GTE', 'value': since_ms}]},
            {'filters': base_filters + [{'propertyName': 'closedate', 'operator': 'GTE', 'value': since_ms}]},
        ],
        'properties': DEAL_PROPS,
        'sorts': [{'propertyName': 'createdate', 'direction': 'DESCENDING'}],
        'limit': 100,
    }
    deals, after = [], None
    while True:
        if after:
            body['after'] = after
        resp = s.post(f'{BASE}/crm/v3/objects/deals/search', json=body, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        deals.extend(data.get('results', []))
        after = data.get('paging', {}).get('next', {}).get('after')
        if not after or len(deals) >= 500:
            break
    # A deal can match both filter groups
    return list({d['id']: d for d in deals}.values())


def batch_associations(s, from_type, to_type, ids, errors=None):
    """Returns {from_id: [{'id': to_id, 'type_ids': {...}}]}. Failed calls are appended to `errors`."""
    out = {}
    url = f'{BASE}/crm/v4/associations/{from_type}/{to_type}/batch/read'
    for i in range(0, len(ids), 100):
        chunk = ids[i:i + 100]
        resp = s.post(url, json={'inputs': [{'id': str(x)} for x in chunk]}, timeout=30)
        if not resp.ok and resp.status_code != 207 and errors is not None:
            errors.append(resp.status_code)
        if resp.ok:
            for item in resp.json().get('results', []):
                out[str(item['from']['id'])] = [
                    {'id': str(t['toObjectId']),
                     'type_ids': {at.get('typeId') for at in t.get('associationTypes', [])
                                  if at.get('category') == 'HUBSPOT_DEFINED'},
                     'labels': {(at.get('label') or '').lower() for at in t.get('associationTypes', []) if at.get('label')}}
                    for t in item.get('to', [])
                ]
    return out


def batch_read(s, object_type, ids, props, errors=None):
    """Returns {id: properties}. Failed calls are appended to `errors`."""
    out = {}
    ids = list(ids)
    for i in range(0, len(ids), 100):
        chunk = ids[i:i + 100]
        resp = s.post(f'{BASE}/crm/v3/objects/{object_type}/batch/read', json={
            'inputs': [{'id': str(x)} for x in chunk], 'properties': props,
        }, timeout=30)
        if not resp.ok and resp.status_code != 207 and errors is not None:
            errors.append(resp.status_code)
        if resp.ok:
            for r in resp.json().get('results', []):
                out[str(r['id'])] = r.get('properties', {})
    return out


def to_int(v):
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return None


# ── Guideline checks ──────────────────────────────────────────────────────────
# Single registry: the "Checks" tab lists it and check_deal() flags deals with it.
# scope: '<deal status> · <pipeline>' where the check applies; severity: error | warning; section: how-to card to fix it.

CHECKS = [
    # New business — signed deals (Closed won and after)
    {'id': 'nb_total_dealerships', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': '"Total number of dealerships in group" is empty', 'why': 'Needed to measure group coverage. Set 1 if single location.'},
    {'id': 'nb_deal_dealerships', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': '"Number of dealerships involved in this deal" is empty', 'why': 'Tells how many locations this contract covers. Set 1 if single location.'},
    {'id': 'nb_deal_gt_group', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': 'More dealerships in the deal than in the group', 'why': 'A deal cannot cover more locations than the group has: one of the two numbers is wrong.'},
    {'id': 'nb_products', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': '"[Cars] Products" is empty', 'why': 'Say what is being sold: App, API, 360…'},
    {'id': 'nb_legal_name', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': '"[CC] Company legal name" is empty', 'why': 'Printed on the invoice.'},
    {'id': 'nb_no_company', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': 'No company associated to the deal', 'why': 'Every deal must be linked to its company (and to every location it covers).'},
    {'id': 'nb_no_contact', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Create a deal',
     'title': 'No contact associated to the deal', 'why': 'Every deal must be linked to a contact.'},
    {'id': 'nb_no_showroom', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Build the quote and line items',
     'title': 'No showroom line item (Closed won / Onboarding)', 'why': 'Every new business contract needs a showroom line item so onboarding can set it up.'},
    {'id': 'nb_won_dms', 'scope': 'Signed deals · New business', 'severity': 'error', 'section': 'Close a deal as won',
     'title': 'DMS is empty', 'why': 'The CSM needs the DMS for the technical integration.'},
    # Renewals & upsells — signed deals
    {'id': 'ren_type', 'scope': 'Signed deals · Renewals & upsells', 'severity': 'error', 'section': 'Create an upsell, downsell or amendment',
     'title': '"Renewal type" is empty', 'why': 'Upsell, downsell, amendment… drives how the contract is replaced.'},
    {'id': 'ren_parent', 'scope': 'Signed deals · Renewals & upsells', 'severity': 'error', 'section': 'Create an upsell, downsell or amendment',
     'title': 'Not linked to the previous deal with the "Parent deal" label', 'why': 'Without it the old contract is not stopped and the client can be billed twice.'},
    {'id': 'ren_new_deal_name', 'scope': 'Signed deals · Renewals & upsells', 'severity': 'warning', 'section': 'Create an upsell, downsell or amendment',
     'title': 'Named "New Deal" but in Renewals & upsells', 'why': 'Check it really replaces an existing contract and is not new business.'},
    # Both pipelines — signed deals
    {'id': 'won_dms_other', 'scope': 'Signed deals · Both pipelines', 'severity': 'warning', 'section': 'Close a deal as won',
     'title': 'DMS set to "Other"', 'why': 'Be specific: the CSM needs the real DMS.'},
    {'id': 'won_no_line_items', 'scope': 'Signed deals · Both pipelines', 'severity': 'error', 'section': 'Build the quote and line items',
     'title': 'No line items', 'why': 'No line items = no ARR and no subscription.'},
    {'id': 'won_one_time', 'scope': 'Signed deals · Both pipelines', 'severity': 'error', 'section': 'Build the quote and line items',
     'title': 'Line item billed "One-time" (set-up fees excluded)', 'why': 'Flagged on API deals, or when every line item is one-time. Not counted as recurring revenue, so not in signings or bonus.'},
    {'id': 'won_no_term', 'scope': 'Signed deals · Both pipelines', 'severity': 'warning', 'section': 'Build the quote and line items',
     'title': 'Recurring line item without a Term', 'why': 'Term = contract duration in months.'},
    {'id': 'won_duration', 'scope': 'Signed deals · Both pipelines', 'severity': 'error', 'section': 'Close a deal as won',
     'title': '"Contract duration (in months)" is empty', 'why': 'Subscription end date and renewal workflows are calculated from it.'},
    {'id': 'won_setup_only_items', 'scope': 'Signed deals · Both pipelines', 'severity': 'error', 'section': 'Build the quote and line items',
     'title': '"Set-up fees only" deal with other line items', 'why': 'A set-up fees only deal may only contain showroom, integration or inventory processing fees, no subscription, flat fee or API.'},
    {'id': 'won_amount', 'scope': 'Signed deals · Both pipelines', 'severity': 'error', 'section': 'Build the quote and line items',
     'title': 'Deal amount is empty or 0', 'why': 'The amount comes from the recurring line items.'},
    # Open deals
    {'id': 'nb_active_client', 'scope': 'Open deals · New business', 'severity': 'warning', 'section': 'Create an upsell, downsell or amendment',
     'title': 'Open deal on a company that is already an active client', 'why': 'If it replaces their current contract, it belongs in Renewals & upsells.'},
    # Lost deals
    {'id': 'nb_lost_reason', 'scope': 'Lost deals · New business', 'severity': 'error', 'section': 'Close lost or disqualify',
     'title': 'Lost without a lost reason', 'why': 'We need to know why we lose.'},
    {'id': 'ren_lost_reason', 'scope': 'Lost deals · Renewals & upsells', 'severity': 'error', 'section': 'Close lost or disqualify',
     'title': 'Churned or lost without a reason', 'why': 'We need to know why clients leave.'},
]
CHECKS_BY_ID = {c['id']: c for c in CHECKS}


def flag(check_id, detail=None):
    """A deal issue, described by its registry entry. `detail` replaces the title when it adds specifics."""
    c = CHECKS_BY_ID[check_id]
    return {'id': check_id,
            'severity': c['severity'],
            'message': detail or c['title'],
            'section': slug(c['section'])}


def check_deal(p, companies, line_items, has_parent_deal):
    """companies / line_items / has_parent_deal are None when HubSpot could not be read: dependent checks are skipped."""
    pipeline, stage = p.get('pipeline'), p.get('dealstage')
    name = p.get('dealname') or ''
    flags = []

    if pipeline == NB_PIPELINE:
        won, lost = stage in NB_WON, stage in NB_LOST

        # Data-entry checks only matter once the deal is signed (Closed won and after)
        if won:
            total = to_int(p.get('number_of_dealerships'))
            in_deal = to_int(p.get('number_of_locations_concerned_by_this_deal'))
            if total is None:
                flags.append(flag('nb_total_dealerships'))
            if in_deal is None:
                flags.append(flag('nb_deal_dealerships'))
            if total is not None and in_deal is not None and in_deal > total:
                flags.append(flag('nb_deal_gt_group', f'{in_deal} dealerships in the deal but only {total} in the group'))
            if not p.get('cars__product'):
                flags.append(flag('nb_products'))
            if not p.get('company_legal_name'):
                flags.append(flag('nb_legal_name'))
            if companies == []:
                flags.append(flag('nb_no_company'))
            if to_int(p.get('num_associated_contacts')) in (None, 0):
                flags.append(flag('nb_no_contact'))
            if not (p.get('dms_ims_multiple_checkboxes') or ''):
                flags.append(flag('nb_won_dms'))
            if stage in (NB_CLOSED_WON, NB_ONBOARDING) and line_items is not None \
                    and not any('showroom' in (li.get('name') or '').lower() for li in line_items):
                flags.append(flag('nb_no_showroom'))
            flags += check_won_common(p, line_items)

        # Open NB deal on a company that is already an active client → probably an upsell
        if not won and not lost:
            active = [c['name'] for c in companies or [] if (c.get('company_activity_status') or '').lower() == 'active']
            if active:
                flags.append(flag('nb_active_client', f'{", ".join(active)} is already an active client: if this replaces their contract it belongs in Renewals & upsells'))

        if lost and not (p.get('closed_lost_reason') or p.get('closed_lost_reason___category')):
            flags.append(flag('nb_lost_reason'))

    elif pipeline == REN_PIPELINE:
        won, lost = stage in REN_WON, stage in REN_LOST
        if won:
            if not p.get('renewal_type'):
                flags.append(flag('ren_type'))
            if has_parent_deal is False:
                flags.append(flag('ren_parent'))
            if 'new deal' in name.lower():
                flags.append(flag('ren_new_deal_name'))
            flags += check_won_common(p, line_items)
        if lost and not (p.get('closed_lost_reason') or p.get('closed_lost_reason___category')):
            flags.append(flag('ren_lost_reason'))

    return flags


def check_won_common(p, line_items):
    flags = []
    setup_only = (p.get('setup_fees_only_no_recurring') or '').lower() == 'true'
    if to_int(p.get('contractdurationinmonths')) is None:
        flags.append(flag('won_duration'))
    if setup_only and line_items:
        wrong = [li.get('name') or '?' for li in line_items
                 if li.get('recurringbillingfrequency')
                 or not any(k in (li.get('name') or '').lower() for k in SETUP_ONLY_KEYWORDS)]
        if wrong:
            flags.append(flag('won_setup_only_items',
                              f'"Set-up fees only" deal with other line items: {", ".join(wrong[:3])}'))
    dms = (p.get('dms_ims_multiple_checkboxes') or '').split(';')
    if 'Other' in dms:
        flags.append(flag('won_dms_other'))

    # Line item count is stored on the deal itself: reliable even when line items can't be read
    count = to_int(p.get('hs_num_of_associated_line_items'))
    if count == 0 or (count is None and line_items == []):
        flags.append(flag('won_no_line_items'))
    if line_items and not setup_only:
        is_api = 'API' in (p.get('cars__product') or '').split(';')
        one_time = [li for li in line_items
                    if not li.get('recurringbillingfrequency') and 'setup' not in (li.get('name') or '').lower().replace('-', '').replace(' ', '')]
        if one_time and (is_api or len(one_time) == len(line_items)):
            names = ', '.join((li.get('name') or '?') for li in one_time[:3])
            flags.append(flag('won_one_time', f'Line item billed "One-time" ({names}): not counted as recurring revenue, so not in your signings or bonus'))
        if any(li.get('recurringbillingfrequency') and not li.get('hs_recurring_billing_period') for li in line_items):
            flags.append(flag('won_no_term'))
    if not setup_only and not to_int(p.get('amount')):
        flags.append(flag('won_amount'))
    return flags


# ── API ───────────────────────────────────────────────────────────────────────

@app.route('/api/guide')
@api_login_required
def guide():
    return jsonify({'howto': HOWTO_MD, 'markdown': GUIDE_MD, 'qa_enabled': bool(os.environ.get('ANTHROPIC_API_KEY'))})


@app.route('/api/checks')
@api_login_required
def checks():
    return jsonify({'checks': [{**c, 'section': slug(c['section'])} for c in CHECKS]})


@app.route('/api/debug/deal-links/<deal_id>')
@api_login_required
def debug_deal_links(deal_id):
    """Raw deal→deal associations (with labels) for one deal, to diagnose the Parent deal check."""
    if not deal_id.isdigit():
        return jsonify({'error': 'deal id must be numeric'}), 400
    resp = make_session().post(f'{BASE}/crm/v4/associations/deals/deals/batch/read',
                               json={'inputs': [{'id': deal_id}]}, timeout=30)
    return jsonify({'status': resp.status_code, 'hubspot': resp.json() if resp.content else None})


@app.route('/api/owners')
@api_login_required
def owners():
    if not TOKEN:
        return jsonify({'error': 'HUBSPOT_API_TOKEN not set'}), 500
    s = make_session()
    out, after = [], None
    while True:
        params = {'limit': 500, 'archived': 'false'}
        if after:
            params['after'] = after
        resp = s.get(f'{BASE}/crm/v3/owners', params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        for o in data.get('results', []):
            teams = [t.get('name', '') for t in o.get('teams', []) or []]
            name = f"{o.get('firstName', '')} {o.get('lastName', '')}".strip() or o.get('email', '')
            if SALES_REPS:
                if not {str(o['id']), (o.get('email') or '').lower(), name.lower()} & SALES_REPS:
                    continue
            elif not any(kw in re.split(r'[^a-z]+', t.lower()) for t in teams for kw in SALES_TEAM_KEYWORDS):
                continue
            out.append({'id': o['id'], 'name': name, 'email': (o.get('email') or '').lower(), 'teams': teams})
        after = data.get('paging', {}).get('next', {}).get('after')
        if not after:
            break
    out.sort(key=lambda o: o['name'].lower())
    return jsonify({'owners': out})


@app.route('/api/my-deals')
@api_login_required
def my_deals():
    if not TOKEN:
        return jsonify({'error': 'HUBSPOT_API_TOKEN not set'}), 500
    owner_id = request.args.get('owner_id', '').strip()
    if not owner_id.isdigit():
        return jsonify({'error': 'owner_id required'}), 400
    days = min(max(int(request.args.get('days', 90)), 7), 365)
    since = datetime.now(timezone.utc) - timedelta(days=days)

    s = make_session()
    raw = search_owner_deals(s, owner_id, since)
    # Skip expired contracts, and renewals auto-generated by workflow and untouched yet (not the rep's data entry)
    raw = [d for d in raw
           if d['properties'].get('dealstage') not in EXPIRED_STAGES
           and not (d['properties'].get('pipeline') == REN_PIPELINE
                    and d['properties'].get('dealstage') == REN_AUTO_STAGE)]
    ids = [d['id'] for d in raw]

    stage_labels = get_stage_labels(s)
    co_err, li_err, dd_err = [], [], []
    deal_companies = batch_associations(s, 'deals', 'companies', ids, co_err)
    deal_line_items = batch_associations(s, 'deals', 'line_items', ids, li_err)
    ren_ids = [d['id'] for d in raw if d['properties'].get('pipeline') == REN_PIPELINE]
    deal_deals = batch_associations(s, 'deals', 'deals', ren_ids, dd_err)

    company_ids = {a['id'] for lst in deal_companies.values() for a in lst}
    companies = batch_read(s, 'companies', company_ids, ['name', 'company_activity_status'], co_err)
    li_ids = {a['id'] for lst in deal_line_items.values() for a in lst}
    line_items = batch_read(s, 'line_items', li_ids, ['name', 'recurringbillingfrequency', 'hs_recurring_billing_period'], li_err)

    # Never report an issue we could not verify: say what was skipped instead
    notices = []
    if co_err:
        notices.append(f'Companies could not be read from HubSpot (HTTP {co_err[0]}): company checks were skipped. '
                       'The HubSpot token needs the crm.objects.companies.read scope.')
    if li_err:
        notices.append(f'Line item details could not be read from HubSpot (HTTP {li_err[0]}): "One-time" and "Term" checks were skipped. '
                       'The HubSpot token needs the crm.objects.line_items.read scope (or e-commerce).')
    if dd_err:
        notices.append(f'Links between deals could not be read from HubSpot (HTTP {dd_err[0]}): the "Parent deal" check was skipped.')

    results = []
    for d in raw:
        p = d['properties']
        did = str(d['id'])
        cos = None if co_err else [{'id': a['id'], **companies.get(a['id'], {})} for a in deal_companies.get(did, [])]
        lis = None if li_err else [line_items[a['id']] for a in deal_line_items.get(did, []) if a['id'] in line_items]
        has_parent = None if dd_err else any(PARENT_LABEL_WORD in l for a in deal_deals.get(did, []) for l in a['labels'])
        flags = check_deal(p, cos, lis, has_parent)
        results.append({
            'id': did,
            'name': p.get('dealname') or '(no name)',
            'pipeline': 'New business' if p.get('pipeline') == NB_PIPELINE else 'Renewals & upsells',
            'stage': stage_labels.get(p.get('dealstage'), p.get('dealstage')),
            'created': (p.get('createdate') or '')[:10],
            'amount': p.get('amount'),
            'currency': p.get('deal_currency_code') or '',
            'company': ', '.join(c.get('name') or '' for c in cos or []),
            'url': HUBSPOT_DEAL_URL.format(id=did),
            'flags': flags,
        })

    # Most errors first, newest first within the same count
    results.sort(key=lambda r: r['created'], reverse=True)
    results.sort(key=lambda r: (-sum(f['severity'] == 'error' for f in r['flags']), -len(r['flags'])))
    n_err = sum(1 for r in results for f in r['flags'] if f['severity'] == 'error')
    n_warn = sum(1 for r in results for f in r['flags'] if f['severity'] == 'warning')
    return jsonify({
        'deals': results,
        'notices': notices,
        'summary': {'deals': len(results), 'clean': sum(1 for r in results if not r['flags']),
                    'errors': n_err, 'warnings': n_warn, 'days': days},
    })


QA_SYSTEM = f"""You are the CRM coach of CarCutter's US Account Executives. You answer questions about how to use HubSpot at CarCutter.

Your users are AEs in the US. They have no BDR: they prospect, qualify, demo and close themselves, so BDR tasks (lead handling, qualification info, logging demos) are theirs too. Frame answers for them; skip rules that only concern BDR attribution or the EU team.

Answer ONLY from the guide below. If the guide does not cover the question, say so plainly and suggest asking Sales Ops (Romane) or the #cc-import-requests Slack channel for import requests. Never invent a process, property name or rule.

Style: short and practical, like a helpful colleague. Give the exact steps or field values when the guide has them. Use bullet points for steps. Reply in the language of the question. End with the name of the guide section you used, formatted as: Source: <section name>.

<guide>
{HOWTO_MD}

{GUIDE_MD}
</guide>"""

_claude = None


def claude_client():
    global _claude
    if _claude is None:
        _claude = anthropic.Anthropic()
    return _claude


@app.route('/api/ask', methods=['POST'])
@api_login_required
def ask():
    if not os.environ.get('ANTHROPIC_API_KEY'):
        return jsonify({'error': 'ANTHROPIC_API_KEY not set'}), 500
    body = request.get_json(silent=True) or {}
    question = (body.get('question') or '').strip()[:2000]
    if not question:
        return jsonify({'error': 'Empty question'}), 400

    # Short conversation memory sent by the browser (last few turns)
    history = []
    for m in (body.get('history') or [])[-6:]:
        if m.get('role') in ('user', 'assistant') and isinstance(m.get('content'), str):
            history.append({'role': m['role'], 'content': m['content'][:4000]})
    if history and history[0]['role'] != 'user':
        history = history[1:]

    try:
        response = claude_client().beta.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=4000,
            betas=['server-side-fallback-2026-07-01'],
            fallbacks='default',
            output_config={'effort': 'low'},
            system=[{'type': 'text', 'text': QA_SYSTEM, 'cache_control': {'type': 'ephemeral'}}],
            messages=history + [{'role': 'user', 'content': question}],
        )
    except anthropic.RateLimitError:
        return jsonify({'error': 'Too many questions right now, try again in a minute.'}), 429
    except anthropic.APIStatusError as e:
        return jsonify({'error': f'Claude API error ({e.status_code}): {e.message}'}), 502
    except anthropic.APIConnectionError:
        return jsonify({'error': 'Could not reach the Claude API.'}), 502

    if response.stop_reason == 'refusal':
        return jsonify({'answer': "I can't answer that one. Please ask Sales Ops directly."})
    answer = ''.join(b.text for b in response.content if b.type == 'text').strip()
    return jsonify({'answer': answer})


@app.route('/')
@login_required
def index():
    return send_from_directory('static', 'index.html')


if __name__ == '__main__':
    app.run(debug=True, port=5001)
