import os
import re
import requests
import anthropic
from datetime import datetime, timedelta, timezone
from pathlib import Path
from flask import Flask, jsonify, send_from_directory, request, session, redirect, url_for, render_template_string
from dotenv import load_dotenv
from functools import wraps

load_dotenv()

app = Flask(__name__, static_folder='static')
app.secret_key = os.environ.get('SECRET_KEY', 'crm-sales-training-2026')

PASSWORD = os.environ.get('APP_PASSWORD', 'CCsales2026$')

TOKEN = os.environ.get('HUBSPOT_API_TOKEN', '')
BASE  = 'https://api.hubapi.com'

CLAUDE_MODEL = os.environ.get('CLAUDE_MODEL', 'claude-opus-5')

GUIDE_MD = (Path(__file__).parent / 'guidelines.md').read_text(encoding='utf-8')

# Owners are listed in the "Mes deals" picker when one of their HubSpot teams matches
SALES_TEAM_KEYWORDS = [k.strip().lower() for k in
                       os.environ.get('SALES_TEAM_KEYWORDS', 'sales,ae,bdr,smb').split(',') if k.strip()]

# Pipelines / stages (CarCutter)
NB_PIPELINE  = '56609227'    # CarCutter - New business
REN_PIPELINE = '228462803'   # CarCutter - Renewals & upsells

NB_WON   = {'141401056', '142518229', '142518230', '5108653252'}  # Closed won, Onboarding, Contract is live, Contract has expired
NB_LOST  = {'141401057', '198382838'}                            # Closed lost, Rejected by AE
REN_WON  = {'390658251', '5600993472', '5600993473'}              # Closed won, Contract is live, Contract has expired
REN_LOST = {'390658252', '3504160964'}                           # Churned, Closed lost
REN_AUTO_STAGE = '390658246'                                     # Deal created (renewals generated by workflow)

PARENT_DEAL_TYPE_ID = 10  # deal→deal HUBSPOT_DEFINED label "Parent deal"

DEAL_PROPS = [
    'dealname', 'pipeline', 'dealstage', 'hubspot_owner_id', 'createdate', 'closedate', 'amount',
    'deal_currency_code', 'number_of_dealerships', 'number_of_locations_concerned_by_this_deal',
    'oem_brand', 'cars__product', 'company_legal_name', 'dms_ims_multiple_checkboxes',
    'revoke_auto_renew', 'renewal_type', 'num_associated_contacts', 'hs_pinned_engagement_id',
    'closed_lost_reason', 'closed_lost_reason___category',
]


# ── Auth ──────────────────────────────────────────────────────────────────────

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('authenticated'):
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated


def api_login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('authenticated'):
            return jsonify({'error': 'Unauthorized'}), 401
        return f(*args, **kwargs)
    return decorated


LOGIN_HTML = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>CRM Sales Training — Login</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 min-h-screen flex items-center justify-center">
  <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-10 w-full max-w-sm">
    <h1 class="text-xl font-bold text-gray-800 mb-1">CRM Sales Training</h1>
    <p class="text-sm text-gray-400 mb-6">Enter the password to continue</p>
    {% if error %}
    <p class="text-sm text-red-500 mb-4 bg-red-50 px-3 py-2 rounded-lg">Wrong password</p>
    {% endif %}
    <form method="post">
      <input type="password" name="password" autofocus placeholder="Password"
        class="w-full border border-gray-200 rounded-lg px-4 py-2.5 text-sm mb-4 focus:outline-none focus:ring-2 focus:ring-indigo-300"/>
      <button type="submit"
        class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2.5 rounded-lg text-sm transition">
        Continue
      </button>
    </form>
  </div>
</body>
</html>'''


@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        if request.form.get('password') == PASSWORD:
            session['authenticated'] = True
            return redirect(url_for('index'))
        return render_template_string(LOGIN_HTML, error=True)
    return render_template_string(LOGIN_HTML, error=False)


@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login'))


@app.errorhandler(Exception)
def handle_any_error(e):
    import traceback
    traceback.print_exc()
    return jsonify({'error': f'{type(e).__name__}: {e}'}), 500


# ── HubSpot helpers ───────────────────────────────────────────────────────────

def make_session():
    s = requests.Session()
    s.headers.update({'Authorization': f'Bearer {TOKEN}'})
    return s


def slug(text):
    """Same slug as static/index.html so rules can link to a guide section."""
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


def get_stage_labels(s):
    resp = s.get(f'{BASE}/crm/v3/pipelines/deals', timeout=15)
    out = {}
    if resp.ok:
        for p in resp.json().get('results', []):
            for st in p.get('stages', []):
                out[st['id']] = st.get('label', st['id'])
    return out


def search_owner_deals(s, owner_id, since):
    """Deals of this owner in NB / Renewals created OR closed since `since`."""
    since_ms = str(int(since.timestamp() * 1000))
    base_filters = [
        {'propertyName': 'hubspot_owner_id', 'operator': 'EQ', 'value': str(owner_id)},
        {'propertyName': 'pipeline', 'operator': 'IN', 'values': [NB_PIPELINE, REN_PIPELINE]},
    ]
    body = {
        'filterGroups': [
            {'filters': base_filters + [{'propertyName': 'createdate', 'operator': 'GTE', 'value': since_ms}]},
            {'filters': base_filters + [{'propertyName': 'closedate', 'operator': 'GTE', 'value': since_ms}]},
        ],
        'properties': DEAL_PROPS,
        'sorts': [{'propertyName': 'createdate', 'direction': 'DESCENDING'}],
        'limit': 100,
    }
    deals, after = [], None
    while True:
        if after:
            body['after'] = after
        resp = s.post(f'{BASE}/crm/v3/objects/deals/search', json=body, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        deals.extend(data.get('results', []))
        after = data.get('paging', {}).get('next', {}).get('after')
        if not after or len(deals) >= 500:
            break
    # A deal can match both filter groups
    return list({d['id']: d for d in deals}.values())


def batch_associations(s, from_type, to_type, ids):
    """Returns {from_id: [{'id': to_id, 'type_ids': {...}}]}."""
    out = {}
    url = f'{BASE}/crm/v4/associations/{from_type}/{to_type}/batch/read'
    for i in range(0, len(ids), 100):
        chunk = ids[i:i + 100]
        resp = s.post(url, json={'inputs': [{'id': str(x)} for x in chunk]}, timeout=30)
        if resp.ok:
            for item in resp.json().get('results', []):
                out[str(item['from']['id'])] = [
                    {'id': str(t['toObjectId']),
                     'type_ids': {at.get('typeId') for at in t.get('associationTypes', [])
                                  if at.get('category') == 'HUBSPOT_DEFINED'}}
                    for t in item.get('to', [])
                ]
    return out


def batch_read(s, object_type, ids, props):
    out = {}
    ids = list(ids)
    for i in range(0, len(ids), 100):
        chunk = ids[i:i + 100]
        resp = s.post(f'{BASE}/crm/v3/objects/{object_type}/batch/read', json={
            'inputs': [{'id': str(x)} for x in chunk], 'properties': props,
        }, timeout=30)
        if resp.ok:
            for r in resp.json().get('results', []):
                out[str(r['id'])] = r.get('properties', {})
    return out


def to_int(v):
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return None


# ── Guideline checks ──────────────────────────────────────────────────────────
# Each flag: severity (error|warning), message, and the guide section it relates to.

def flag(severity, message, section):
    return {'severity': severity, 'message': message, 'section': slug(section)}


def check_deal(p, companies, line_items, has_parent_deal):
    pipeline, stage = p.get('pipeline'), p.get('dealstage')
    name = p.get('dealname') or ''
    flags = []

    if pipeline == NB_PIPELINE:
        won, lost = stage in NB_WON, stage in NB_LOST
        total = to_int(p.get('number_of_dealerships'))
        in_deal = to_int(p.get('number_of_locations_concerned_by_this_deal'))

        if total is None:
            flags.append(flag('error', '"Total number of dealerships in group" is empty (set 1 if single location).', 'Creating a deal'))
        if in_deal is None:
            flags.append(flag('error', '"Number of dealerships involved in this deal" is empty (set 1 if single location).', 'Creating a deal'))
        if total is not None and in_deal is not None and in_deal > total:
            flags.append(flag('error', f'{in_deal} dealerships in the deal but only {total} in the group: the deal cannot cover more than the group.', 'Creating a deal'))
        if not p.get('cars__product'):
            flags.append(flag('error', '"[Cars] Products" is empty.', 'Creating a deal'))
        if not p.get('company_legal_name'):
            flags.append(flag('error' if won else 'warning', '"[CC] Company legal name" is empty (it is printed on the invoice).', 'Creating a deal'))
        if not p.get('oem_brand'):
            flags.append(flag('warning', '"Affiliated brands" is empty (official franchise brands only).', 'Creating a deal'))
        if not companies:
            flags.append(flag('error', 'No company associated to the deal.', 'Creating a deal'))
        if to_int(p.get('num_associated_contacts')) in (None, 0):
            flags.append(flag('error', 'No contact associated to the deal.', 'Creating a deal'))

        # Open NB deal on a company that is already an active client → probably an upsell
        if not won and not lost:
            active = [c['name'] for c in companies if (c.get('company_activity_status') or '').lower() == 'active']
            if active:
                flags.append(flag('warning', f'{", ".join(active)} is already an active client: if this is an upsell/renewal it belongs in the Renewals & upsells pipeline.', 'Renewals & upsells'))

        if won:
            flags += check_won_common(p, line_items)
            if not (p.get('dms_ims_multiple_checkboxes') or ''):
                flags.append(flag('error', 'DMS is empty at Closed Won: the CSM needs it for the integration.', 'Handover to CSM'))

        if lost and not (p.get('closed_lost_reason') or p.get('closed_lost_reason___category')):
            flags.append(flag('error', 'Closed lost without a lost reason.', 'Closed lost'))

    elif pipeline == REN_PIPELINE:
        won, lost = stage in REN_WON, stage in REN_LOST
        if not p.get('renewal_type'):
            flags.append(flag('error', '"Renewal type" is empty.', 'Renewals & upsells'))
        if not has_parent_deal:
            flags.append(flag('error', 'Not linked to the previous deal with the "Parent deal" label.', 'Renewals & upsells'))
        if 'new deal' in name.lower():
            flags.append(flag('warning', 'Named "New Deal" but in Renewals & upsells: check it is really a renewal/upsell and not new business.', 'Renewals & upsells'))
        if won:
            flags += check_won_common(p, line_items)
        if lost and not (p.get('closed_lost_reason') or p.get('closed_lost_reason___category')):
            flags.append(flag('error', 'Closed lost / churned without a lost reason.', 'Closed lost'))

    return flags


def check_won_common(p, line_items):
    flags = []
    dms = (p.get('dms_ims_multiple_checkboxes') or '').split(';')
    if 'Other' in dms:
        flags.append(flag('warning', 'DMS set to "Other": be specific, the CSM needs it for the integration.', 'Handover to CSM'))
    if not p.get('revoke_auto_renew'):
        flags.append(flag('warning', '"Revoke auto-renew?" is empty: it defines the renewal rules.', 'Handover to CSM'))
    if not p.get('hs_pinned_engagement_id'):
        flags.append(flag('warning', 'No pinned handover note for the CSM.', 'Handover to CSM'))

    if not line_items:
        flags.append(flag('error', 'Closed won without line items: ARR cannot be calculated.', 'Quotes, line items & ARR'))
    else:
        is_api = 'API' in (p.get('cars__product') or '').split(';')
        one_time = [li for li in line_items
                    if not li.get('recurringbillingfrequency') and 'setup' not in (li.get('name') or '').lower().replace('-', '').replace(' ', '')]
        if one_time and (is_api or len(one_time) == len(line_items)):
            names = ', '.join((li.get('name') or '?') for li in one_time[:3])
            flags.append(flag('error', f'Line item billed "One-time" ({names}): not counted as recurring revenue, so not in your signings or bonus.', 'Quotes, line items & ARR'))
        if any(li.get('recurringbillingfrequency') and not li.get('hs_recurring_billing_period') for li in line_items):
            flags.append(flag('warning', 'A recurring line item has no Term set.', 'Quotes, line items & ARR'))
    if not to_int(p.get('amount')):
        flags.append(flag('error', 'Deal amount is empty or 0.', 'Quotes, line items & ARR'))
    return flags


# ── API ───────────────────────────────────────────────────────────────────────

@app.route('/api/guide')
@api_login_required
def guide():
    return jsonify({'markdown': GUIDE_MD})


@app.route('/api/owners')
@api_login_required
def owners():
    if not TOKEN:
        return jsonify({'error': 'HUBSPOT_API_TOKEN not set'}), 500
    s = make_session()
    out, after = [], None
    while True:
        params = {'limit': 500, 'archived': 'false'}
        if after:
            params['after'] = after
        resp = s.get(f'{BASE}/crm/v3/owners', params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        for o in data.get('results', []):
            teams = [t.get('name', '') for t in o.get('teams', []) or []]
            if not any(kw in re.split(r'[^a-z]+', t.lower()) for t in teams for kw in SALES_TEAM_KEYWORDS):
                continue
            name = f"{o.get('firstName', '')} {o.get('lastName', '')}".strip() or o.get('email', '')
            out.append({'id': o['id'], 'name': name, 'teams': teams})
        after = data.get('paging', {}).get('next', {}).get('after')
        if not after:
            break
    out.sort(key=lambda o: o['name'].lower())
    return jsonify({'owners': out})


@app.route('/api/my-deals')
@api_login_required
def my_deals():
    if not TOKEN:
        return jsonify({'error': 'HUBSPOT_API_TOKEN not set'}), 500
    owner_id = request.args.get('owner_id', '').strip()
    if not owner_id.isdigit():
        return jsonify({'error': 'owner_id required'}), 400
    days = min(max(int(request.args.get('days', 90)), 7), 365)
    since = datetime.now(timezone.utc) - timedelta(days=days)

    s = make_session()
    raw = search_owner_deals(s, owner_id, since)
    # Renewals auto-generated by workflow and untouched yet are not the rep's data entry
    raw = [d for d in raw if not (d['properties'].get('pipeline') == REN_PIPELINE
                                  and d['properties'].get('dealstage') == REN_AUTO_STAGE)]
    ids = [d['id'] for d in raw]

    stage_labels = get_stage_labels(s)
    deal_companies = batch_associations(s, 'deals', 'companies', ids)
    deal_line_items = batch_associations(s, 'deals', 'line_items', ids)
    ren_ids = [d['id'] for d in raw if d['properties'].get('pipeline') == REN_PIPELINE]
    deal_deals = batch_associations(s, 'deals', 'deals', ren_ids)

    company_ids = {a['id'] for lst in deal_companies.values() for a in lst}
    companies = batch_read(s, 'companies', company_ids, ['name', 'company_activity_status'])
    li_ids = {a['id'] for lst in deal_line_items.values() for a in lst}
    line_items = batch_read(s, 'line_items', li_ids, ['name', 'recurringbillingfrequency', 'hs_recurring_billing_period'])

    results = []
    for d in raw:
        p = d['properties']
        did = str(d['id'])
        cos = [{'id': a['id'], **companies.get(a['id'], {})} for a in deal_companies.get(did, [])]
        lis = [line_items[a['id']] for a in deal_line_items.get(did, []) if a['id'] in line_items]
        has_parent = any(PARENT_DEAL_TYPE_ID in a['type_ids'] for a in deal_deals.get(did, []))
        flags = check_deal(p, cos, lis, has_parent)
        results.append({
            'id': did,
            'name': p.get('dealname') or '(no name)',
            'pipeline': 'New business' if p.get('pipeline') == NB_PIPELINE else 'Renewals & upsells',
            'stage': stage_labels.get(p.get('dealstage'), p.get('dealstage')),
            'created': (p.get('createdate') or '')[:10],
            'amount': p.get('amount'),
            'currency': p.get('deal_currency_code') or '',
            'company': ', '.join(c.get('name') or '' for c in cos),
            'flags': flags,
        })

    # Most errors first, newest first within the same count
    results.sort(key=lambda r: r['created'], reverse=True)
    results.sort(key=lambda r: (-sum(f['severity'] == 'error' for f in r['flags']), -len(r['flags'])))
    n_err = sum(1 for r in results for f in r['flags'] if f['severity'] == 'error')
    n_warn = sum(1 for r in results for f in r['flags'] if f['severity'] == 'warning')
    return jsonify({
        'deals': results,
        'summary': {'deals': len(results), 'clean': sum(1 for r in results if not r['flags']),
                    'errors': n_err, 'warnings': n_warn, 'days': days},
    })


QA_SYSTEM = f"""You are the CRM coach of CarCutter's sales team (BDRs, AEs, SMB reps). You answer questions about how to use HubSpot at CarCutter.

Answer ONLY from the guide below. If the guide does not cover the question, say so plainly and suggest asking Sales Ops (Romane) or the #cc-import-requests Slack channel for import requests. Never invent a process, property name or rule.

Style: short and practical, like a helpful colleague. Give the exact steps or field values when the guide has them. Use bullet points for steps. Reply in the language of the question. End with the name of the guide section you used, formatted as: Source: <section name>.

<guide>
{GUIDE_MD}
</guide>"""

_claude = None


def claude_client():
    global _claude
    if _claude is None:
        _claude = anthropic.Anthropic()
    return _claude


@app.route('/api/ask', methods=['POST'])
@api_login_required
def ask():
    if not os.environ.get('ANTHROPIC_API_KEY'):
        return jsonify({'error': 'ANTHROPIC_API_KEY not set'}), 500
    body = request.get_json(silent=True) or {}
    question = (body.get('question') or '').strip()[:2000]
    if not question:
        return jsonify({'error': 'Empty question'}), 400

    # Short conversation memory sent by the browser (last few turns)
    history = []
    for m in (body.get('history') or [])[-6:]:
        if m.get('role') in ('user', 'assistant') and isinstance(m.get('content'), str):
            history.append({'role': m['role'], 'content': m['content'][:4000]})
    if history and history[0]['role'] != 'user':
        history = history[1:]

    try:
        response = claude_client().beta.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=4000,
            betas=['server-side-fallback-2026-07-01'],
            fallbacks='default',
            output_config={'effort': 'low'},
            system=[{'type': 'text', 'text': QA_SYSTEM, 'cache_control': {'type': 'ephemeral'}}],
            messages=history + [{'role': 'user', 'content': question}],
        )
    except anthropic.RateLimitError:
        return jsonify({'error': 'Too many questions right now, try again in a minute.'}), 429
    except anthropic.APIStatusError as e:
        return jsonify({'error': f'Claude API error ({e.status_code}): {e.message}'}), 502
    except anthropic.APIConnectionError:
        return jsonify({'error': 'Could not reach the Claude API.'}), 502

    if response.stop_reason == 'refusal':
        return jsonify({'answer': "I can't answer that one. Please ask Sales Ops directly."})
    answer = ''.join(b.text for b in response.content if b.type == 'text').strip()
    return jsonify({'answer': answer})


@app.route('/')
@login_required
def index():
    return send_from_directory('static', 'index.html')


if __name__ == '__main__':
    app.run(debug=True, port=5001)
